GET http://localhost:3001/api/blogs
###
GET http://localhost:3001/api/users
###
POST http://localhost:3001/api/blogs
content-type: application/json

{
    "title":"Nice People",
    "author":"Roald Dahl",
    "url": "http://meep.com",
    "likes": 9,
    "userId":"642bcdea9911a097d5a8996f"
}

###
POST http://localhost:3001/api/users
content-type: application/json

{
    "name":"Bro Man",
    "username":"bman",
    "password": "bye"
}


###
GET http://localhost:3001/api/users

###
POST http://localhost:3001/api/login
content-type: application/json

{
    "username": "cjbro",
    "password": "hello"
}

###
POST http://localhost:3001/api/login
content-type: application/json

{
    "username": "bman",
    "password": "bye"
}

###
POST http://localhost:3001/api/blogs
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImJtYW4iLCJpZCI6IjY0MmJmMDhiYWM1ZGVjZjQ3MjMwY2Q0NCIsImlhdCI6MTY4MDYwMTMwNX0.6Df6raY-qkYVj3fE9dTOiLbQ5d6MLsMPDLPklR5dovU

{
    "title":"User Extraction Works",
    "author":"Boo Man",
    "url": "http://meep.com",
    "likes": 9
}

###
DELETE  http://localhost:3001/api/blogs/642be5ec9d347d0f13bd2f6b
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImJtYW4iLCJpZCI6IjY0MmJmMDhiYWM1ZGVjZjQ3MjMwY2Q0NCIsImlhdCI6MTY4MDYwMTMwNX0.6Df6raY-qkYVj3fE9dTOiLbQ5d6MLsMPDLPklR5dovU
###
PUT http://localhost:3001/api/blogs/642ec62de8dffc5303ecc0a0
content-type: application/json

{
    "likes": 9
}
